"""Every builtin's arity must match Microsoft's own Syntax block.

The defect class: an INVENTED SIGNATURE. The name is real, so
`test_catalog.py`'s name gate cannot see it. The behaviour is right for the
arguments that ARE accepted, so no behavioural test sees it. It shows only as
"the call the documentation shows does not work here" - the first thing a user
tries.

`Duration.FromText` and `Oracle.Database` were each found by hand, one release
apart. Finding the third by hand was not a plan, so the question is asked of
every builtin at once, from a checked-in harvest of the Syntax blocks
(`tests/fixtures/m-signatures.json`, regenerated by
`scripts/harvest_signatures.py`). The fixture is the source of truth so this
runs offline.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from pqtools.evaluate import BUILTINS

_ROOT = Path(__file__).resolve().parent.parent
_FIXTURE = _ROOT / "tests" / "fixtures" / "m-signatures.json"
_SRC = _ROOT / "src" / "pqtools"

SIGNATURES: dict[str, dict] = json.loads(_FIXTURE.read_text(encoding="utf-8"))

# `_arity("Name", args, low)` or `_arity("Name", args, low, high)`. Only a
# LITERAL call can be compared; a computed bound is skipped rather than
# guessed at.
_ARITY_CALL = re.compile(
    r'_arity\(\s*"([^"]+)"\s*,\s*args\s*,\s*(\d+)(?:\s*,\s*(\d+))?\s*\)'
)


def _implemented_arities() -> dict[str, tuple[int, int]]:
    found: dict[str, tuple[int, int]] = {}
    for path in sorted(_SRC.rglob("*.py")):
        for match in _ARITY_CALL.finditer(path.read_text(encoding="utf-8")):
            low = int(match.group(2))
            high = int(match.group(3)) if match.group(3) else low
            found[match.group(1)] = (low, high)
    return found


IMPLEMENTED = _implemented_arities()

# Names whose implemented arity deliberately differs from the page, each with
# the reason. A name may only sit here because the DOCUMENT is the thing that
# cannot be honoured - never because the code has not caught up.
_DELIBERATE: dict[str, str] = {}

_COMPARABLE = sorted(
    name
    for name in BUILTINS
    if name in SIGNATURES and name in IMPLEMENTED and name not in _DELIBERATE
)


# The M hash-literals are language SYNTAX, not library functions: they have no
# entry in the function reference and so no Syntax block to harvest. They are
# not unverified - the worked-example corpus exercises them 367 times.
_HASH_LITERALS = frozenset(
    {"#binary", "#date", "#datetime", "#datetimezone", "#duration", "#table", "#time"}
)


def test_every_callable_builtin_has_a_harvested_signature() -> None:
    """The gate's own blind spot: a builtin whose page is not cached is
    silently skipped by the parametrised checks above, so the suite would go
    green having asked nothing about it.

    Enum and type VALUES are exempt by construction - they are plain values
    (`Order.Ascending` is 0), not callables, and have no signature to state.
    """
    unverified = sorted(
        name
        for name, value in BUILTINS.items()
        if callable(value) and name not in SIGNATURES and name not in _HASH_LITERALS
    )
    assert unverified == [], (
        f"{len(unverified)} callable builtin(s) have no harvested signature, so "
        f"nothing checks their arity or nullability: {unverified}. Refresh the "
        "doc cache and re-run scripts/harvest_signatures.py, or - if the name "
        "genuinely has no reference page - say so explicitly here."
    )


def test_the_fixture_covers_most_of_the_registry() -> None:
    # A harvester that silently stopped parsing would turn this whole module
    # into a no-op that still passes - the failure mode a gate must not have.
    assert len(_COMPARABLE) > 400, (
        f"only {len(_COMPARABLE)} builtins are comparable; the signature "
        "harvest or the _arity scan has stopped working"
    )


@pytest.mark.parametrize("name", _COMPARABLE)
def test_arity_matches_the_documented_signature(name: str) -> None:
    documented = tuple(SIGNATURES[name]["arity"])
    assert IMPLEMENTED[name] == documented, (
        f"{name} accepts {IMPLEMENTED[name][0]}..{IMPLEMENTED[name][1]} "
        f"arguments but the documented signature is "
        f"{documented[0]}..{documented[1]}: "
        f"{name}({', '.join(_render(p) for p in SIGNATURES[name]['parameters'])})"
    )


def _render(parameter: dict) -> str:
    prefix = "optional " if parameter["optional"] else ""
    return f"{prefix}{parameter['name']} as {parameter['type']}"


# --------------------------------------------------------------------------
# The same fixture answers a second question: a parameter declared `nullable`
# accepts null.
# --------------------------------------------------------------------------

# One literal per M type, so a call can be synthesised for the arguments that
# are NOT under test. A type with no entry makes the builtin inconclusive
# rather than failed - a gate must not report a defect it cannot see.
_LITERAL = {
    "text": '"a"',
    "number": "1",
    "logical": "true",
    "list": "{1}",
    "record": "[a=1]",
    "table": '#table({"a"},{{1}})',
    "date": "#date(2020,1,1)",
    "time": "#time(1,0,0)",
    "datetime": "#datetime(2020,1,1,0,0,0)",
    "datetimezone": "#datetimezone(2020,1,1,0,0,0,0,0)",
    "duration": "#duration(0,1,0,0)",
    "function": "each _",
    "type": "type any",
    "any": "1",
    "binary": "#binary({1})",
}

_GOT_NULL = re.compile(r"got null|expected .*\bnull\b", re.IGNORECASE)


def _literal(type_text: str) -> str | None:
    return _LITERAL.get(type_text.lower().removeprefix("nullable ").strip())


def _null_first_argument_calls() -> list[tuple[str, str]]:
    calls: list[tuple[str, str]] = []
    for name, signature in sorted(SIGNATURES.items()):
        parameters = signature["parameters"]
        required = signature["arity"][0]
        if not parameters or name not in BUILTINS or not callable(BUILTINS[name]):
            continue
        # BOTH halves of the declaration have to say null is in play: a
        # nullable input AND a nullable result. `Table.RowCount(table as
        # table) as number` says neither and is not asked the question.
        if not parameters[0]["type"].lower().startswith("nullable "):
            continue
        if not signature["returns"].lower().startswith("nullable "):
            continue
        others = [_literal(p["type"]) for p in parameters[1:required]]
        if any(other is None for other in others):
            continue
        calls.append((name, f"{name}({', '.join(['null', *others])})"))
    return calls


NULL_CALLS = _null_first_argument_calls()


def test_the_null_probe_covers_a_real_share_of_the_registry() -> None:
    assert len(NULL_CALLS) > 60, (
        f"only {len(NULL_CALLS)} builtins are probed for null propagation; "
        "the synthesiser has stopped working"
    )


@pytest.mark.parametrize("name,call", NULL_CALLS, ids=[n for n, _ in NULL_CALLS])
def test_a_nullable_first_argument_accepts_null(name: str, call: str) -> None:
    """`f(null)` must not be "expected text, got null" when the page says
    `f(text as nullable text) as nullable text`.

    Fourteen builtins refused null while ninety-seven accepted it - the same
    inconsistency fourteen times, each individually plausible, none visible
    to a test. See `_shared._null_propagates`.
    """
    from pqtools import evaluate

    try:
        evaluate(call)
    except Exception as error:  # noqa: BLE001 - the message is the assertion
        message = f"{type(error).__name__}: {error}"
        assert not _GOT_NULL.search(message), (
            f"{call} was refused for being null, but the documented signature "
            f"is {name}({_render(SIGNATURES[name]['parameters'][0])}) as "
            f"{SIGNATURES[name]['returns']}: {message}"
        )
