"""Every function Microsoft's M reference documents, and why we do or don't run it.

The point of this file is the quality of one error message.

Before it existed, `Salesforce.Data(...)` raised `unknown identifier:
Salesforce.Data` - the same error a typo produces. A reader cannot tell from
that whether they misspelled something, whether pqtools is broken, or whether
the function is real but unimplemented. Meanwhile `SharePoint.Files` got a
proper typed refusal explaining itself, because someone had listed it by hand.

README.md and llms.txt both promise that any construct pqtools cannot evaluate
"raises a typed error naming it". For roughly six hundred documented functions
that promise was not being kept.

So this catalog names every documented function and the reason it is not
implemented. It is consulted ONLY when a name is absent from ``BUILTINS``,
which makes it self-maintaining: implement a function and it stops being
consulted for that name, with nothing to remember to delete. That property is
deliberate - the previous hand-maintained list had already drifted.

Regenerate with ``python scripts/sync_m_catalog.py`` (see that script for the
Microsoft Learn pages it reads). Do not hand-edit the DOCUMENTED table.
"""

from __future__ import annotations

# Why a documented function is not implemented. The text is user-facing: it
# appears in the error, so it has to say what the reader should do next.
REASONS: dict[str, str] = {
    "connector": (
        "is a data-source connector. It needs vendor credentials, an OAuth "
        "identity, or a proprietary driver that pqtools does not ship. Supply "
        "its result with --bind NAME=PATH and pqtools will run every step "
        "after it"
    ),
    "folding": (
        "exists to control query folding - pushing work into a remote engine. "
        "pqtools evaluates locally and never folds, so there is nothing "
        "honest for it to do here"
    ),
    "engine": (
        "is evaluated by Power Query's Mashup Engine itself, not by the M "
        "standard library. pqtools has no equivalent to expose"
    ),
    "model": (
        "reads a Power BI data model (relationships, keys, partitions) that a "
        "standalone M evaluator does not have"
    ),
    "fuzzy": (
        "does approximate matching. Microsoft does not document the "
        "similarity algorithm precisely enough to reproduce, and an "
        "approximate join returns the WRONG ROWS rather than an error - so "
        "pqtools refuses instead of guessing"
    ),
    "culture": (
        "is culture-sensitive. pqtools implements the invariant/en-US culture "
        "only; another culture would silently return differently ordered or "
        "differently parsed results"
    ),
    "notyet": (
        "is a documented Power Query function that pqtools has not "
        "implemented yet. It is a real function and your query is not wrong. "
        "Please open an issue at https://github.com/GopalGB/pqtools/issues"
    ),
    "shape": (
        "reads a format pqtools could parse, but Microsoft does not document "
        "the SHAPE of the table it returns - no column names, no worked "
        "output. Guessing the shape is worse than refusing: the parse would "
        "succeed and the next step, which navigates by column name, would "
        "silently read the wrong thing"
    ),
    "internal": (
        "is marked 'intended for internal use only' in Microsoft's own "
        "reference, so its behaviour is not specified for callers"
    ),
}

# name -> key in REASONS. Generated; see the module docstring.
DOCUMENTED: dict[str, str] = {
    "Access.Database": "connector",
    "AccessControlEntry.ConditionToIdentities": "engine",
    "ActiveDirectory.Domains": "connector",
    "AdoDotNet.DataSource": "connector",
    "AdoDotNet.Query": "connector",
    "AdobeAnalytics.Cubes": "connector",
    "AnalysisServices.Database": "connector",
    "AnalysisServices.Databases": "connector",
    "AzureStorage.BlobContents": "connector",
    "AzureStorage.Blobs": "connector",
    "AzureStorage.DataLake": "connector",
    "AzureStorage.DataLakeContents": "connector",
    "AzureStorage.Tables": "connector",
    "Binary.ApproximateLength": "notyet",
    "Binary.Buffer": "notyet",
    "Binary.Combine": "notyet",
    "Binary.Compress": "notyet",
    "Binary.Decompress": "notyet",
    "Binary.From": "notyet",
    "Binary.FromList": "notyet",
    "Binary.FromText": "notyet",
    "Binary.InferContentType": "notyet",
    "Binary.Length": "notyet",
    "Binary.Range": "notyet",
    "Binary.Split": "notyet",
    "Binary.ToList": "notyet",
    "Binary.ToText": "notyet",
    "Binary.View": "notyet",
    "Binary.ViewError": "notyet",
    "Binary.ViewFunction": "notyet",
    "BinaryFormat.Binary": "notyet",
    "BinaryFormat.Byte": "notyet",
    "BinaryFormat.ByteOrder": "notyet",
    "BinaryFormat.Choice": "notyet",
    "BinaryFormat.Decimal": "notyet",
    "BinaryFormat.Double": "notyet",
    "BinaryFormat.Group": "notyet",
    "BinaryFormat.Length": "notyet",
    "BinaryFormat.List": "notyet",
    "BinaryFormat.Null": "notyet",
    "BinaryFormat.Record": "notyet",
    "BinaryFormat.SignedInteger16": "notyet",
    "BinaryFormat.SignedInteger32": "notyet",
    "BinaryFormat.SignedInteger64": "notyet",
    "BinaryFormat.Single": "notyet",
    "BinaryFormat.Text": "notyet",
    "BinaryFormat.Transform": "notyet",
    "BinaryFormat.UnsignedInteger16": "notyet",
    "BinaryFormat.UnsignedInteger32": "notyet",
    "BinaryFormat.UnsignedInteger64": "notyet",
    "Byte.From": "notyet",
    "Cdm.Contents": "connector",
    "Character.FromNumber": "notyet",
    "Character.ToNumber": "notyet",
    "Combiner.CombineTextByDelimiter": "notyet",
    "Combiner.CombineTextByEachDelimiter": "notyet",
    "Combiner.CombineTextByLengths": "notyet",
    "Combiner.CombineTextByPositions": "notyet",
    "Combiner.CombineTextByRanges": "notyet",
    "Comparer.Equals": "notyet",
    "Comparer.FromCulture": "culture",
    "Comparer.Ordinal": "notyet",
    "Comparer.OrdinalIgnoreCase": "notyet",
    "Csv.Document": "connector",
    "Cube.AddAndExpandDimensionColumn": "model",
    "Cube.AddMeasureColumn": "model",
    "Cube.ApplyParameter": "model",
    "Cube.AttributeMemberId": "model",
    "Cube.AttributeMemberProperty": "model",
    "Cube.CollapseAndRemoveColumns": "model",
    "Cube.Dimensions": "model",
    "Cube.DisplayFolders": "model",
    "Cube.MeasureProperties": "model",
    "Cube.MeasureProperty": "model",
    "Cube.Measures": "model",
    "Cube.Parameters": "model",
    "Cube.Properties": "model",
    "Cube.PropertyKey": "model",
    "Cube.ReplaceDimensions": "model",
    "Cube.Transform": "model",
    "Currency.From": "notyet",
    "DB2.Database": "connector",
    "Date.AddDays": "notyet",
    "Date.AddMonths": "notyet",
    "Date.AddQuarters": "notyet",
    "Date.AddWeeks": "notyet",
    "Date.AddYears": "notyet",
    "Date.Day": "notyet",
    "Date.DayOfWeek": "notyet",
    "Date.DayOfWeekName": "notyet",
    "Date.DayOfYear": "notyet",
    "Date.DaysInMonth": "notyet",
    "Date.EndOfDay": "notyet",
    "Date.EndOfMonth": "notyet",
    "Date.EndOfQuarter": "notyet",
    "Date.EndOfWeek": "notyet",
    "Date.EndOfYear": "notyet",
    "Date.From": "notyet",
    "Date.FromText": "notyet",
    "Date.IsInCurrentDay": "notyet",
    "Date.IsInCurrentMonth": "notyet",
    "Date.IsInCurrentQuarter": "notyet",
    "Date.IsInCurrentWeek": "notyet",
    "Date.IsInCurrentYear": "notyet",
    "Date.IsInNextDay": "notyet",
    "Date.IsInNextMonth": "notyet",
    "Date.IsInNextNDays": "notyet",
    "Date.IsInNextNMonths": "notyet",
    "Date.IsInNextNQuarters": "notyet",
    "Date.IsInNextNWeeks": "notyet",
    "Date.IsInNextNYears": "notyet",
    "Date.IsInNextQuarter": "notyet",
    "Date.IsInNextWeek": "notyet",
    "Date.IsInNextYear": "notyet",
    "Date.IsInPreviousDay": "notyet",
    "Date.IsInPreviousMonth": "notyet",
    "Date.IsInPreviousNDays": "notyet",
    "Date.IsInPreviousNMonths": "notyet",
    "Date.IsInPreviousNQuarters": "notyet",
    "Date.IsInPreviousNWeeks": "notyet",
    "Date.IsInPreviousNYears": "notyet",
    "Date.IsInPreviousQuarter": "notyet",
    "Date.IsInPreviousWeek": "notyet",
    "Date.IsInPreviousYear": "notyet",
    "Date.IsInYearToDate": "notyet",
    "Date.IsLeapYear": "notyet",
    "Date.Month": "notyet",
    "Date.MonthName": "notyet",
    "Date.QuarterOfYear": "notyet",
    "Date.StartOfDay": "notyet",
    "Date.StartOfMonth": "notyet",
    "Date.StartOfQuarter": "notyet",
    "Date.StartOfWeek": "notyet",
    "Date.StartOfYear": "notyet",
    "Date.ToRecord": "notyet",
    "Date.ToText": "notyet",
    "Date.WeekOfMonth": "notyet",
    "Date.WeekOfYear": "notyet",
    "Date.Year": "notyet",
    "DateTime.AddZone": "notyet",
    "DateTime.Date": "notyet",
    "DateTime.FixedLocalNow": "notyet",
    "DateTime.From": "notyet",
    "DateTime.FromFileTime": "notyet",
    "DateTime.FromText": "notyet",
    "DateTime.IsInCurrentHour": "notyet",
    "DateTime.IsInCurrentMinute": "notyet",
    "DateTime.IsInCurrentSecond": "notyet",
    "DateTime.IsInNextHour": "notyet",
    "DateTime.IsInNextMinute": "notyet",
    "DateTime.IsInNextNHours": "notyet",
    "DateTime.IsInNextNMinutes": "notyet",
    "DateTime.IsInNextNSeconds": "notyet",
    "DateTime.IsInNextSecond": "notyet",
    "DateTime.IsInPreviousHour": "notyet",
    "DateTime.IsInPreviousMinute": "notyet",
    "DateTime.IsInPreviousNHours": "notyet",
    "DateTime.IsInPreviousNMinutes": "notyet",
    "DateTime.IsInPreviousNSeconds": "notyet",
    "DateTime.IsInPreviousSecond": "notyet",
    "DateTime.LocalNow": "notyet",
    "DateTime.Time": "notyet",
    "DateTime.ToRecord": "notyet",
    "DateTime.ToText": "notyet",
    "DateTimeZone.FixedLocalNow": "notyet",
    "DateTimeZone.FixedUtcNow": "notyet",
    "DateTimeZone.From": "notyet",
    "DateTimeZone.FromFileTime": "notyet",
    "DateTimeZone.FromText": "notyet",
    "DateTimeZone.LocalNow": "notyet",
    "DateTimeZone.RemoveZone": "notyet",
    "DateTimeZone.SwitchZone": "notyet",
    "DateTimeZone.ToLocal": "notyet",
    "DateTimeZone.ToRecord": "notyet",
    "DateTimeZone.ToText": "notyet",
    "DateTimeZone.ToUtc": "notyet",
    "DateTimeZone.UtcNow": "notyet",
    "DateTimeZone.ZoneHours": "notyet",
    "DateTimeZone.ZoneMinutes": "notyet",
    "Decimal.From": "notyet",
    "DeltaLake.Metadata": "connector",
    "DeltaLake.Table": "connector",
    "Diagnostics.ActivityId": "notyet",
    "Diagnostics.CorrelationId": "notyet",
    "Diagnostics.Trace": "notyet",
    "Double.From": "notyet",
    "Duration.Days": "notyet",
    "Duration.From": "notyet",
    "Duration.FromText": "notyet",
    "Duration.Hours": "notyet",
    "Duration.Minutes": "notyet",
    "Duration.Seconds": "notyet",
    "Duration.ToRecord": "notyet",
    "Duration.ToText": "notyet",
    "Duration.TotalDays": "notyet",
    "Duration.TotalHours": "notyet",
    "Duration.TotalMinutes": "notyet",
    "Duration.TotalSeconds": "notyet",
    "Embedded.Value": "notyet",
    "Error.Record": "notyet",
    "Essbase.Cubes": "connector",
    "Excel.CurrentWorkbook": "engine",
    "Excel.Workbook": "connector",
    "Exchange.Contents": "connector",
    "Expression.Constant": "notyet",
    "Expression.Evaluate": "notyet",
    "Expression.Identifier": "notyet",
    "FabricAI.Prompt": "connector",
    "File.Contents": "connector",
    "Folder.Contents": "connector",
    "Folder.Files": "connector",
    "Function.From": "notyet",
    "Function.Invoke": "notyet",
    "Function.InvokeAfter": "notyet",
    "Function.IsDataSource": "notyet",
    "Function.ScalarVector": "notyet",
    "Geography.FromWellKnownText": "notyet",
    "Geography.ToWellKnownText": "notyet",
    "GeographyPoint.From": "notyet",
    "Geometry.FromWellKnownText": "notyet",
    "Geometry.ToWellKnownText": "notyet",
    "GeometryPoint.From": "notyet",
    "GoogleAnalytics.Accounts": "connector",
    "Guid.From": "notyet",
    "HdInsight.Containers": "connector",
    "HdInsight.Contents": "connector",
    "HdInsight.Files": "connector",
    "Hdfs.Contents": "connector",
    "Hdfs.Files": "connector",
    "Html.Table": "shape",
    "Identity.From": "engine",
    "Identity.IsMemberOf": "engine",
    "IdentityProvider.Default": "engine",
    "Informix.Database": "connector",
    "Int16.From": "notyet",
    "Int32.From": "notyet",
    "Int64.From": "notyet",
    "Int8.From": "notyet",
    "ItemExpression.From": "engine",
    "Json.Document": "connector",
    "Json.FromValue": "notyet",
    "Lines.FromBinary": "notyet",
    "Lines.FromText": "notyet",
    "Lines.ToBinary": "notyet",
    "Lines.ToText": "notyet",
    "List.Accumulate": "notyet",
    "List.AllTrue": "notyet",
    "List.Alternate": "notyet",
    "List.AnyTrue": "notyet",
    "List.Average": "notyet",
    "List.Buffer": "notyet",
    "List.Combine": "notyet",
    "List.Contains": "notyet",
    "List.ContainsAll": "notyet",
    "List.ContainsAny": "notyet",
    "List.Count": "notyet",
    "List.Covariance": "notyet",
    "List.DateTimeZones": "notyet",
    "List.DateTimes": "notyet",
    "List.Dates": "notyet",
    "List.Difference": "notyet",
    "List.Distinct": "notyet",
    "List.Durations": "notyet",
    "List.FindText": "notyet",
    "List.First": "notyet",
    "List.FirstN": "notyet",
    "List.Generate": "notyet",
    "List.InsertRange": "notyet",
    "List.Intersect": "notyet",
    "List.IsDistinct": "notyet",
    "List.IsEmpty": "notyet",
    "List.Last": "notyet",
    "List.LastN": "notyet",
    "List.MatchesAll": "notyet",
    "List.MatchesAny": "notyet",
    "List.Max": "notyet",
    "List.MaxN": "notyet",
    "List.Median": "notyet",
    "List.Min": "notyet",
    "List.MinN": "notyet",
    "List.Mode": "notyet",
    "List.Modes": "notyet",
    "List.NonNullCount": "notyet",
    "List.Numbers": "notyet",
    "List.Percentile": "notyet",
    "List.PositionOf": "notyet",
    "List.PositionOfAny": "notyet",
    "List.Positions": "notyet",
    "List.Product": "notyet",
    "List.Random": "notyet",
    "List.Range": "notyet",
    "List.RemoveFirstN": "notyet",
    "List.RemoveItems": "notyet",
    "List.RemoveLastN": "notyet",
    "List.RemoveMatchingItems": "notyet",
    "List.RemoveNulls": "notyet",
    "List.RemoveRange": "notyet",
    "List.Repeat": "notyet",
    "List.ReplaceMatchingItems": "notyet",
    "List.ReplaceRange": "notyet",
    "List.ReplaceValue": "notyet",
    "List.Reverse": "notyet",
    "List.Select": "notyet",
    "List.Single": "notyet",
    "List.SingleOrDefault": "notyet",
    "List.Skip": "notyet",
    "List.Sort": "notyet",
    "List.Split": "notyet",
    "List.StandardDeviation": "notyet",
    "List.Sum": "notyet",
    "List.Times": "notyet",
    "List.Transform": "notyet",
    "List.TransformMany": "notyet",
    "List.Union": "notyet",
    "List.Zip": "notyet",
    "Logical.From": "notyet",
    "Logical.FromText": "notyet",
    "Logical.ToText": "notyet",
    "Module.Versions": "notyet",
    "MySQL.Database": "connector",
    "Number.Abs": "notyet",
    "Number.Acos": "notyet",
    "Number.Asin": "notyet",
    "Number.Atan": "notyet",
    "Number.Atan2": "notyet",
    "Number.BitwiseAnd": "notyet",
    "Number.BitwiseNot": "notyet",
    "Number.BitwiseOr": "notyet",
    "Number.BitwiseShiftLeft": "notyet",
    "Number.BitwiseShiftRight": "notyet",
    "Number.BitwiseXor": "notyet",
    "Number.Combinations": "notyet",
    "Number.Cos": "notyet",
    "Number.Cosh": "notyet",
    "Number.Exp": "notyet",
    "Number.Factorial": "notyet",
    "Number.From": "notyet",
    "Number.FromText": "notyet",
    "Number.IntegerDivide": "notyet",
    "Number.IsEven": "notyet",
    "Number.IsNaN": "notyet",
    "Number.IsOdd": "notyet",
    "Number.Ln": "notyet",
    "Number.Log": "notyet",
    "Number.Log10": "notyet",
    "Number.Mod": "notyet",
    "Number.Permutations": "notyet",
    "Number.Power": "notyet",
    "Number.Random": "notyet",
    "Number.RandomBetween": "notyet",
    "Number.Round": "notyet",
    "Number.RoundAwayFromZero": "notyet",
    "Number.RoundDown": "notyet",
    "Number.RoundTowardZero": "notyet",
    "Number.RoundUp": "notyet",
    "Number.Sign": "notyet",
    "Number.Sin": "notyet",
    "Number.Sinh": "notyet",
    "Number.Sqrt": "notyet",
    "Number.Tan": "notyet",
    "Number.Tanh": "notyet",
    "Number.ToText": "notyet",
    "OData.Feed": "connector",
    "Odbc.DataSource": "connector",
    "Odbc.InferOptions": "connector",
    "Odbc.Query": "connector",
    "OleDb.DataSource": "connector",
    "OleDb.Query": "connector",
    "Oracle.Database": "connector",
    "Pdf.Tables": "shape",
    "Percentage.From": "notyet",
    "PostgreSQL.Database": "connector",
    "RData.FromBinary": "connector",
    "Record.AddField": "notyet",
    "Record.Combine": "notyet",
    "Record.Field": "notyet",
    "Record.FieldCount": "notyet",
    "Record.FieldNames": "notyet",
    "Record.FieldOrDefault": "notyet",
    "Record.FieldValues": "notyet",
    "Record.FromList": "notyet",
    "Record.FromTable": "notyet",
    "Record.HasFields": "notyet",
    "Record.RemoveFields": "notyet",
    "Record.RenameFields": "notyet",
    "Record.ReorderFields": "notyet",
    "Record.SelectFields": "notyet",
    "Record.ToList": "notyet",
    "Record.ToTable": "notyet",
    "Record.TransformFields": "notyet",
    "Replacer.ReplaceText": "notyet",
    "Replacer.ReplaceValue": "notyet",
    "RowExpression.Column": "engine",
    "RowExpression.From": "engine",
    "Salesforce.Data": "connector",
    "Salesforce.Reports": "connector",
    "SapBusinessWarehouse.Cubes": "connector",
    "SapHana.Database": "connector",
    "SharePoint.Contents": "connector",
    "SharePoint.Files": "connector",
    "SharePoint.Tables": "connector",
    "Single.From": "notyet",
    "Soda.Feed": "connector",
    "Splitter.SplitByNothing": "notyet",
    "Splitter.SplitTextByAnyDelimiter": "notyet",
    "Splitter.SplitTextByCharacterTransition": "notyet",
    "Splitter.SplitTextByDelimiter": "notyet",
    "Splitter.SplitTextByEachDelimiter": "notyet",
    "Splitter.SplitTextByLengths": "notyet",
    "Splitter.SplitTextByPositions": "notyet",
    "Splitter.SplitTextByRanges": "notyet",
    "Splitter.SplitTextByRepeatedLengths": "notyet",
    "Splitter.SplitTextByWhitespace": "notyet",
    "Sql.Database": "connector",
    "Sql.Databases": "connector",
    "Sybase.Database": "connector",
    "Table.AddColumn": "notyet",
    "Table.AddFuzzyClusterColumn": "fuzzy",
    "Table.AddIndexColumn": "notyet",
    "Table.AddJoinColumn": "notyet",
    "Table.AddKey": "notyet",
    "Table.AddRankColumn": "notyet",
    "Table.AggregateTableColumn": "notyet",
    "Table.AlternateRows": "notyet",
    "Table.ApproximateRowCount": "notyet",
    "Table.Buffer": "notyet",
    "Table.Column": "notyet",
    "Table.ColumnCount": "notyet",
    "Table.ColumnNames": "notyet",
    "Table.ColumnsOfType": "notyet",
    "Table.Combine": "notyet",
    "Table.CombineColumns": "notyet",
    "Table.CombineColumnsToRecord": "notyet",
    "Table.Contains": "notyet",
    "Table.ContainsAll": "notyet",
    "Table.ContainsAny": "notyet",
    "Table.DemoteHeaders": "notyet",
    "Table.Distinct": "notyet",
    "Table.DuplicateColumn": "notyet",
    "Table.ExpandListColumn": "notyet",
    "Table.ExpandRecordColumn": "notyet",
    "Table.ExpandTableColumn": "notyet",
    "Table.FillDown": "notyet",
    "Table.FillUp": "notyet",
    "Table.FindText": "notyet",
    "Table.First": "notyet",
    "Table.FirstN": "notyet",
    "Table.FirstValue": "notyet",
    "Table.FromColumns": "notyet",
    "Table.FromList": "notyet",
    "Table.FromPartitions": "notyet",
    "Table.FromRecords": "notyet",
    "Table.FromRows": "notyet",
    "Table.FromValue": "notyet",
    "Table.FuzzyGroup": "fuzzy",
    "Table.FuzzyJoin": "fuzzy",
    "Table.FuzzyNestedJoin": "fuzzy",
    "Table.Group": "notyet",
    "Table.HasColumns": "notyet",
    "Table.InsertRows": "notyet",
    "Table.IsDistinct": "notyet",
    "Table.IsEmpty": "notyet",
    "Table.Join": "notyet",
    "Table.Keys": "notyet",
    "Table.Last": "notyet",
    "Table.LastN": "notyet",
    "Table.MatchesAllRows": "notyet",
    "Table.MatchesAnyRows": "notyet",
    "Table.Max": "notyet",
    "Table.MaxN": "notyet",
    "Table.Min": "notyet",
    "Table.MinN": "notyet",
    "Table.NestedJoin": "notyet",
    "Table.Partition": "notyet",
    "Table.PartitionKey": "notyet",
    "Table.PartitionValues": "notyet",
    "Table.Pivot": "notyet",
    "Table.PositionOf": "notyet",
    "Table.PositionOfAny": "notyet",
    "Table.PrefixColumns": "notyet",
    "Table.Profile": "notyet",
    "Table.PromoteHeaders": "notyet",
    "Table.Range": "notyet",
    "Table.RemoveColumns": "notyet",
    "Table.RemoveFirstN": "notyet",
    "Table.RemoveLastN": "notyet",
    "Table.RemoveMatchingRows": "notyet",
    "Table.RemoveRows": "notyet",
    "Table.RemoveRowsWithErrors": "notyet",
    "Table.RenameColumns": "notyet",
    "Table.ReorderColumns": "notyet",
    "Table.Repeat": "notyet",
    "Table.ReplaceErrorValues": "notyet",
    "Table.ReplaceKeys": "notyet",
    "Table.ReplaceMatchingRows": "notyet",
    "Table.ReplacePartitionKey": "notyet",
    "Table.ReplaceRows": "notyet",
    "Table.ReplaceValue": "notyet",
    "Table.ReverseRows": "notyet",
    "Table.RowCount": "notyet",
    "Table.Schema": "notyet",
    "Table.SelectColumns": "notyet",
    "Table.SelectRows": "notyet",
    "Table.SelectRowsWithErrors": "notyet",
    "Table.SingleRow": "notyet",
    "Table.Skip": "notyet",
    "Table.Sort": "notyet",
    "Table.Split": "notyet",
    "Table.SplitAt": "notyet",
    "Table.SplitColumn": "notyet",
    "Table.StopFolding": "folding",
    "Table.ToColumns": "notyet",
    "Table.ToList": "notyet",
    "Table.ToRecords": "notyet",
    "Table.ToRows": "notyet",
    "Table.TransformColumnNames": "notyet",
    "Table.TransformColumnTypes": "notyet",
    "Table.TransformColumns": "notyet",
    "Table.TransformRows": "notyet",
    "Table.Transpose": "notyet",
    "Table.Unpivot": "notyet",
    "Table.UnpivotOtherColumns": "notyet",
    "Table.View": "folding",
    "Table.ViewError": "folding",
    "Table.ViewFunction": "folding",
    "Tables.GetRelationships": "model",
    "Teradata.Database": "connector",
    "Text.AfterDelimiter": "notyet",
    "Text.At": "notyet",
    "Text.BeforeDelimiter": "notyet",
    "Text.BetweenDelimiters": "notyet",
    "Text.Clean": "notyet",
    "Text.Combine": "notyet",
    "Text.Contains": "notyet",
    "Text.End": "notyet",
    "Text.EndsWith": "notyet",
    "Text.From": "notyet",
    "Text.FromBinary": "notyet",
    "Text.InferNumberType": "notyet",
    "Text.Insert": "notyet",
    "Text.Length": "notyet",
    "Text.Lower": "notyet",
    "Text.Middle": "notyet",
    "Text.NewGuid": "notyet",
    "Text.PadEnd": "notyet",
    "Text.PadStart": "notyet",
    "Text.PositionOf": "notyet",
    "Text.PositionOfAny": "notyet",
    "Text.Proper": "notyet",
    "Text.Range": "notyet",
    "Text.Remove": "notyet",
    "Text.RemoveRange": "notyet",
    "Text.Repeat": "notyet",
    "Text.Replace": "notyet",
    "Text.ReplaceRange": "notyet",
    "Text.Reverse": "notyet",
    "Text.Select": "notyet",
    "Text.Split": "notyet",
    "Text.SplitAny": "notyet",
    "Text.Start": "notyet",
    "Text.StartsWith": "notyet",
    "Text.ToBinary": "notyet",
    "Text.ToList": "notyet",
    "Text.Trim": "notyet",
    "Text.TrimEnd": "notyet",
    "Text.TrimStart": "notyet",
    "Text.Upper": "notyet",
    "Time.EndOfHour": "notyet",
    "Time.From": "notyet",
    "Time.FromText": "notyet",
    "Time.Hour": "notyet",
    "Time.Minute": "notyet",
    "Time.Second": "notyet",
    "Time.StartOfHour": "notyet",
    "Time.ToRecord": "notyet",
    "Time.ToText": "notyet",
    "Type.AddTableKey": "notyet",
    "Type.ClosedRecord": "notyet",
    "Type.Facets": "notyet",
    "Type.ForFunction": "notyet",
    "Type.ForRecord": "notyet",
    "Type.FunctionParameters": "notyet",
    "Type.FunctionRequiredParameters": "notyet",
    "Type.FunctionReturn": "notyet",
    "Type.Is": "notyet",
    "Type.IsNullable": "notyet",
    "Type.IsOpenRecord": "notyet",
    "Type.ListItem": "notyet",
    "Type.NonNullable": "notyet",
    "Type.OpenRecord": "notyet",
    "Type.RecordFields": "notyet",
    "Type.ReplaceFacets": "notyet",
    "Type.ReplaceTableKeys": "notyet",
    "Type.ReplaceTablePartitionKey": "notyet",
    "Type.TableColumn": "notyet",
    "Type.TableKeys": "notyet",
    "Type.TablePartitionKey": "notyet",
    "Type.TableRow": "notyet",
    "Type.TableSchema": "notyet",
    "Type.Union": "notyet",
    "Uri.BuildQueryString": "notyet",
    "Uri.Combine": "notyet",
    "Uri.EscapeDataString": "notyet",
    "Uri.Parts": "notyet",
    "Value.Add": "notyet",
    "Value.Alternates": "notyet",
    "Value.As": "notyet",
    "Value.Compare": "notyet",
    "Value.Divide": "notyet",
    "Value.Equals": "notyet",
    "Value.Expression": "notyet",
    "Value.FromText": "notyet",
    "Value.Is": "notyet",
    "Value.Metadata": "notyet",
    "Value.Multiply": "notyet",
    "Value.NativeQuery": "folding",
    "Value.NullableEquals": "notyet",
    "Value.Optimize": "folding",
    "Value.RemoveMetadata": "notyet",
    "Value.ReplaceMetadata": "notyet",
    "Value.ReplaceType": "notyet",
    "Value.Subtract": "notyet",
    "Value.Type": "notyet",
    "Value.VersionIdentity": "notyet",
    "Value.Versions": "notyet",
    "Variable.Value": "notyet",
    "Variable.ValueOrDefault": "notyet",
    "Web.BrowserContents": "connector",
    "Web.Contents": "connector",
    "Web.Headers": "connector",
    "Web.Page": "connector",
    "WebAction.Request": "connector",
    "Xml.Document": "shape",
    "Xml.Tables": "shape",
}


def explain(name: str) -> str | None:
    """The refusal message for a documented-but-unimplemented function.

    Returns None for a name Microsoft does not document, which keeps a
    genuine typo reading as a typo - the distinction this file exists to
    draw. Do not make this fall back to a generic message.
    """
    reason = DOCUMENTED.get(name)
    if reason is None:
        return None
    return f"{name} {REASONS[reason]}"


__all__ = ["DOCUMENTED", "REASONS", "explain"]
